# Generated by Django 5.2.4 on 2025-08-05 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
