# Generated by Django 5.2.4 on 2025-08-05 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='cleared_at',
            new_name='completed_at',
        ),
    ]
